services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - nginx_conf/conf.d:/etc/nginx/conf.d
      - nginx_conf/nginx.conf:/etc/nginx/nginx.conf # Монтируем основной конфиг Nginx
      - nginx_conf/letsencrypt:/etc/letsencrypt
    networks:
      - wp-network
    restart: always
    ports:
      - "80:80"
      - "443:443"
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shared_database
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - mariadb_data/config/mariadb.cnf:/etc/mysql/mariadb.cnf   # Монтируем оптимизированный конфиг
      - mariadb_data/data:/var/lib/mysql               # Монтируем данные базы данных
    networks:
      - wp_network
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf  # Указываем путь к кастомной конфигурации
    volumes:
      - redis_data/config/redis.conf:/usr/local/etc/redis/redis.conf  # Монтируем кастомный конфиг
      - redis_data/data:/data  # Монтируем директорию для данных Redis
    networks:
      - wp_network
    restart: always

networks:
  wp_network:
    driver: bridge
